package com.sjq.githubapp.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sjq.githubapp.db.greendao.DemoEntity;
import com.sjq.githubapp.javabean.PopularEntity;
import com.sjq.githubapp.javabean.PopularKeyEntity;
import com.sjq.githubapp.javabean.TrendingEntity;
import com.sjq.githubapp.javabean.TrendingKeyEntity;
import com.sjq.githubapp.javabean.UserContactPopularEntity;
import com.sjq.githubapp.javabean.UserContactPopularKeyEntity;
import com.sjq.githubapp.javabean.UserContactTrendingEntity;
import com.sjq.githubapp.javabean.UserContactTrendingKeyEntity;
import com.sjq.githubapp.javabean.UserEntity;

import com.sjq.githubapp.db.greendao.DemoEntityDao;
import com.sjq.githubapp.db.greendao.PopularEntityDao;
import com.sjq.githubapp.db.greendao.PopularKeyEntityDao;
import com.sjq.githubapp.db.greendao.TrendingEntityDao;
import com.sjq.githubapp.db.greendao.TrendingKeyEntityDao;
import com.sjq.githubapp.db.greendao.UserContactPopularEntityDao;
import com.sjq.githubapp.db.greendao.UserContactPopularKeyEntityDao;
import com.sjq.githubapp.db.greendao.UserContactTrendingEntityDao;
import com.sjq.githubapp.db.greendao.UserContactTrendingKeyEntityDao;
import com.sjq.githubapp.db.greendao.UserEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig demoEntityDaoConfig;
    private final DaoConfig popularEntityDaoConfig;
    private final DaoConfig popularKeyEntityDaoConfig;
    private final DaoConfig trendingEntityDaoConfig;
    private final DaoConfig trendingKeyEntityDaoConfig;
    private final DaoConfig userContactPopularEntityDaoConfig;
    private final DaoConfig userContactPopularKeyEntityDaoConfig;
    private final DaoConfig userContactTrendingEntityDaoConfig;
    private final DaoConfig userContactTrendingKeyEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;

    private final DemoEntityDao demoEntityDao;
    private final PopularEntityDao popularEntityDao;
    private final PopularKeyEntityDao popularKeyEntityDao;
    private final TrendingEntityDao trendingEntityDao;
    private final TrendingKeyEntityDao trendingKeyEntityDao;
    private final UserContactPopularEntityDao userContactPopularEntityDao;
    private final UserContactPopularKeyEntityDao userContactPopularKeyEntityDao;
    private final UserContactTrendingEntityDao userContactTrendingEntityDao;
    private final UserContactTrendingKeyEntityDao userContactTrendingKeyEntityDao;
    private final UserEntityDao userEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        demoEntityDaoConfig = daoConfigMap.get(DemoEntityDao.class).clone();
        demoEntityDaoConfig.initIdentityScope(type);

        popularEntityDaoConfig = daoConfigMap.get(PopularEntityDao.class).clone();
        popularEntityDaoConfig.initIdentityScope(type);

        popularKeyEntityDaoConfig = daoConfigMap.get(PopularKeyEntityDao.class).clone();
        popularKeyEntityDaoConfig.initIdentityScope(type);

        trendingEntityDaoConfig = daoConfigMap.get(TrendingEntityDao.class).clone();
        trendingEntityDaoConfig.initIdentityScope(type);

        trendingKeyEntityDaoConfig = daoConfigMap.get(TrendingKeyEntityDao.class).clone();
        trendingKeyEntityDaoConfig.initIdentityScope(type);

        userContactPopularEntityDaoConfig = daoConfigMap.get(UserContactPopularEntityDao.class).clone();
        userContactPopularEntityDaoConfig.initIdentityScope(type);

        userContactPopularKeyEntityDaoConfig = daoConfigMap.get(UserContactPopularKeyEntityDao.class).clone();
        userContactPopularKeyEntityDaoConfig.initIdentityScope(type);

        userContactTrendingEntityDaoConfig = daoConfigMap.get(UserContactTrendingEntityDao.class).clone();
        userContactTrendingEntityDaoConfig.initIdentityScope(type);

        userContactTrendingKeyEntityDaoConfig = daoConfigMap.get(UserContactTrendingKeyEntityDao.class).clone();
        userContactTrendingKeyEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        demoEntityDao = new DemoEntityDao(demoEntityDaoConfig, this);
        popularEntityDao = new PopularEntityDao(popularEntityDaoConfig, this);
        popularKeyEntityDao = new PopularKeyEntityDao(popularKeyEntityDaoConfig, this);
        trendingEntityDao = new TrendingEntityDao(trendingEntityDaoConfig, this);
        trendingKeyEntityDao = new TrendingKeyEntityDao(trendingKeyEntityDaoConfig, this);
        userContactPopularEntityDao = new UserContactPopularEntityDao(userContactPopularEntityDaoConfig, this);
        userContactPopularKeyEntityDao = new UserContactPopularKeyEntityDao(userContactPopularKeyEntityDaoConfig, this);
        userContactTrendingEntityDao = new UserContactTrendingEntityDao(userContactTrendingEntityDaoConfig, this);
        userContactTrendingKeyEntityDao = new UserContactTrendingKeyEntityDao(userContactTrendingKeyEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);

        registerDao(DemoEntity.class, demoEntityDao);
        registerDao(PopularEntity.class, popularEntityDao);
        registerDao(PopularKeyEntity.class, popularKeyEntityDao);
        registerDao(TrendingEntity.class, trendingEntityDao);
        registerDao(TrendingKeyEntity.class, trendingKeyEntityDao);
        registerDao(UserContactPopularEntity.class, userContactPopularEntityDao);
        registerDao(UserContactPopularKeyEntity.class, userContactPopularKeyEntityDao);
        registerDao(UserContactTrendingEntity.class, userContactTrendingEntityDao);
        registerDao(UserContactTrendingKeyEntity.class, userContactTrendingKeyEntityDao);
        registerDao(UserEntity.class, userEntityDao);
    }
    
    public void clear() {
        demoEntityDaoConfig.clearIdentityScope();
        popularEntityDaoConfig.clearIdentityScope();
        popularKeyEntityDaoConfig.clearIdentityScope();
        trendingEntityDaoConfig.clearIdentityScope();
        trendingKeyEntityDaoConfig.clearIdentityScope();
        userContactPopularEntityDaoConfig.clearIdentityScope();
        userContactPopularKeyEntityDaoConfig.clearIdentityScope();
        userContactTrendingEntityDaoConfig.clearIdentityScope();
        userContactTrendingKeyEntityDaoConfig.clearIdentityScope();
        userEntityDaoConfig.clearIdentityScope();
    }

    public DemoEntityDao getDemoEntityDao() {
        return demoEntityDao;
    }

    public PopularEntityDao getPopularEntityDao() {
        return popularEntityDao;
    }

    public PopularKeyEntityDao getPopularKeyEntityDao() {
        return popularKeyEntityDao;
    }

    public TrendingEntityDao getTrendingEntityDao() {
        return trendingEntityDao;
    }

    public TrendingKeyEntityDao getTrendingKeyEntityDao() {
        return trendingKeyEntityDao;
    }

    public UserContactPopularEntityDao getUserContactPopularEntityDao() {
        return userContactPopularEntityDao;
    }

    public UserContactPopularKeyEntityDao getUserContactPopularKeyEntityDao() {
        return userContactPopularKeyEntityDao;
    }

    public UserContactTrendingEntityDao getUserContactTrendingEntityDao() {
        return userContactTrendingEntityDao;
    }

    public UserContactTrendingKeyEntityDao getUserContactTrendingKeyEntityDao() {
        return userContactTrendingKeyEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

}
