package com.sjq.githubapp.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sjq.githubapp.db.greendao.DemoEntity;
import com.sjq.githubapp.javabean.LanguageEntity;

import com.sjq.githubapp.db.greendao.DemoEntityDao;
import com.sjq.githubapp.db.greendao.LanguageEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig demoEntityDaoConfig;
    private final DaoConfig languageEntityDaoConfig;

    private final DemoEntityDao demoEntityDao;
    private final LanguageEntityDao languageEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        demoEntityDaoConfig = daoConfigMap.get(DemoEntityDao.class).clone();
        demoEntityDaoConfig.initIdentityScope(type);

        languageEntityDaoConfig = daoConfigMap.get(LanguageEntityDao.class).clone();
        languageEntityDaoConfig.initIdentityScope(type);

        demoEntityDao = new DemoEntityDao(demoEntityDaoConfig, this);
        languageEntityDao = new LanguageEntityDao(languageEntityDaoConfig, this);

        registerDao(DemoEntity.class, demoEntityDao);
        registerDao(LanguageEntity.class, languageEntityDao);
    }
    
    public void clear() {
        demoEntityDaoConfig.clearIdentityScope();
        languageEntityDaoConfig.clearIdentityScope();
    }

    public DemoEntityDao getDemoEntityDao() {
        return demoEntityDao;
    }

    public LanguageEntityDao getLanguageEntityDao() {
        return languageEntityDao;
    }

}
